In [1]:
import pandas as pd

In [2]:
#creation of dataframe using dictionary
data = { 'Name': ['Amora', 'Beast', 'Captain America'],
        'Age': [25,30,35],
        'City': ['New York', 'London', 'paris']}
    
df = pd.DataFrame(data)
print(df)

              Name  Age      City
0            Amora   25  New York
1            Beast   30    London
2  Captain America   35     paris

In [4]:
#creation of dataframe of list
data = [['Deadpool', 25, 'New york'],
        ['Elektra', 30, 'London'],
        ['Falcon', 35, 'Paris']]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)

       Name  Age      City
0  Deadpool   25  New york
1   Elektra   30    London
2    Falcon   35     Paris

In [6]:
#creation of dataframe from file
df = pd.read_csv("C://PES/Python Programming/names.csv")
print(df)

   sl     Name  Age           City
0   1     Amar   25       New York
1   2  Biswash   30  San Francisco
2   3     Chay   35    Los Angeles
3   4    Dhruv   29        Chicago
4   5   Eashan   28       New York
5   6   Farhan   23     California
6   7  Gauging   21      Las Vegas

In [9]:
#creating an empty file 
df_empty= pd.DataFrame()
print(df_empty)

Empty DataFrame
Columns: []
Index: []

In [10]:
#display first few rows
df.head()

   sl     Name  Age           City
0   1     Amar   25       New York
1   2  Biswash   30  San Francisco
2   3     Chay   35    Los Angeles
3   4    Dhruv   29        Chicago
4   5   Eashan   28       New York

In [12]:
#display last few rows
df.tail()

   sl     Name  Age         City
2   3     Chay   35  Los Angeles
3   4    Dhruv   29      Chicago
4   5   Eashan   28     New York
5   6   Farhan   23   California
6   7  Gauging   21    Las Vegas

In [13]:
df.shape

(7, 4)

In [14]:
df.columns

Index(['sl', 'Name', 'Age', 'City'], dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [16]:
df.dtypes

sl       int64
Name    object
Age      int64
City    object
dtype: object

In [20]:
df["Age"] = df["Age"].astype('float64')

In [21]:
print(df)

   sl     Name   Age           City
0   1     Amar  25.0       New York
1   2  Biswash  30.0  San Francisco
2   3     Chay  35.0    Los Angeles
3   4    Dhruv  29.0        Chicago
4   5   Eashan  28.0       New York
5   6   Farhan  23.0     California
6   7  Gauging  21.0      Las Vegas

In [22]:
df['Age']

0    25.0
1    30.0
2    35.0
3    29.0
4    28.0
5    23.0
6    21.0
Name: Age, dtype: float64

In [24]:
df[['Name', 'Age']]

      Name   Age
0     Amar  25.0
1  Biswash  30.0
2     Chay  35.0
3    Dhruv  29.0
4   Eashan  28.0
5   Farhan  23.0
6  Gauging  21.0

In [25]:
data = {
    "Prod": ["Mobile", "Laptop", "Headphones", "Charger", "Camerad"]

SyntaxError: incomplete input (2856285514.py, line 2)

In [26]:
df.loc[0:2]

   sl     Name   Age           City
0   1     Amar  25.0       New York
1   2  Biswash  30.0  San Francisco
2   3     Chay  35.0    Los Angeles

In [48]:
data = {
    "Prod": ["Mobile", "Laptop", "Headphones", "Charger", "Camera", "Tablet", "Mouse", "Keyboard", "Monitor", "Speaker"],
    "Qty": [10, None, 5, 3, 2 , None, 7, 4, None, 6],
    "Amount": [12000, 45000, 1500, 1200, 55000, None, 800, 1508, 12, 3200],
    "Region":["south", "north", "west", "east", "south", "north", "west", "east", "south", "west"],
    "Customer": ["Rahul", "SHREYA", "Arjun", "Meera", None, "Rohan", "Anita", "Karthik", None, "Vikram"],
    "City": ["Bengaluru", "Delhi", "Mumbai", "Kolkata", "Chennai", None, "Pune", "Bhubaneswar", None, "Ahmedabad"]}

df=pd.DataFrame(data)
df.to_csv("C://PES/Python Programming/SALEs_data.csv")
print("CSV file created successfully!")

CSV file created successfully!

In [49]:
df_sales = pd.read_csv("C://PES/Python Programming/SALEs_data.csv")
print(df_sales)

   Unnamed: 0        Prod   Qty   Amount Region Customer         City
0           0      Mobile  10.0  12000.0  south    Rahul    Bengaluru
1           1      Laptop   NaN  45000.0  north   SHREYA        Delhi
2           2  Headphones   5.0   1500.0   west    Arjun       Mumbai
3           3     Charger   3.0   1200.0   east    Meera      Kolkata
4           4      Camera   2.0  55000.0  south      NaN      Chennai
5           5      Tablet   NaN      NaN  north    Rohan          NaN
6           6       Mouse   7.0    800.0   west    Anita         Pune
7           7    Keyboard   4.0   1508.0   east  Karthik  Bhubaneswar
8           8     Monitor   NaN     12.0  south      NaN          NaN
9           9     Speaker   6.0   3200.0   west   Vikram    Ahmedabad

In [50]:
#check missing value per column
df_sales.isna().sum()

Unnamed: 0    0
Prod          0
Qty           3
Amount        1
Region        0
Customer      2
City          2
dtype: int64

In [51]:
#check missing value in rows
df_sales.isna().any(axis=1).sum()

4

In [52]:
df_sales.dtypes

Unnamed: 0      int64
Prod           object
Qty           float64
Amount        float64
Region         object
Customer       object
City           object
dtype: object

In [53]:
# in amount column fill missing values with mean or median
df_sales["Amount"] = df["Amount"].fillna(df_sales["Amount"].median())

In [54]:
df_sales

   Unnamed: 0        Prod   Qty   Amount Region Customer         City
0           0      Mobile  10.0  12000.0  south    Rahul    Bengaluru
1           1      Laptop   NaN  45000.0  north   SHREYA        Delhi
2           2  Headphones   5.0   1500.0   west    Arjun       Mumbai
3           3     Charger   3.0   1200.0   east    Meera      Kolkata
4           4      Camera   2.0  55000.0  south      NaN      Chennai
5           5      Tablet   NaN   1508.0  north    Rohan          NaN
6           6       Mouse   7.0    800.0   west    Anita         Pune
7           7    Keyboard   4.0   1508.0   east  Karthik  Bhubaneswar
8           8     Monitor   NaN     12.0  south      NaN          NaN
9           9     Speaker   6.0   3200.0   west   Vikram    Ahmedabad

In [55]:
df_sales["Amount"] = df["Amount"].fillna(df_sales["Amount"].mean())

In [56]:
df_sales

   Unnamed: 0        Prod   Qty   Amount Region Customer         City
0           0      Mobile  10.0  12000.0  south    Rahul    Bengaluru
1           1      Laptop   NaN  45000.0  north   SHREYA        Delhi
2           2  Headphones   5.0   1500.0   west    Arjun       Mumbai
3           3     Charger   3.0   1200.0   east    Meera      Kolkata
4           4      Camera   2.0  55000.0  south      NaN      Chennai
5           5      Tablet   NaN  12172.8  north    Rohan          NaN
6           6       Mouse   7.0    800.0   west    Anita         Pune
7           7    Keyboard   4.0   1508.0   east  Karthik  Bhubaneswar
8           8     Monitor   NaN     12.0  south      NaN          NaN
9           9     Speaker   6.0   3200.0   west   Vikram    Ahmedabad

In [57]:
#To drop a column 
df_sales = df_sales.drop(columns=['City'])

In [58]:
df_sales = df_sales.dropna(axis=1,how='all')
df_sales

   Unnamed: 0        Prod   Qty   Amount Region Customer
0           0      Mobile  10.0  12000.0  south    Rahul
1           1      Laptop   NaN  45000.0  north   SHREYA
2           2  Headphones   5.0   1500.0   west    Arjun
3           3     Charger   3.0   1200.0   east    Meera
4           4      Camera   2.0  55000.0  south      NaN
5           5      Tablet   NaN  12172.8  north    Rohan
6           6       Mouse   7.0    800.0   west    Anita
7           7    Keyboard   4.0   1508.0   east  Karthik
8           8     Monitor   NaN     12.0  south      NaN
9           9     Speaker   6.0   3200.0   west   Vikram

In [59]:
rename_map = {"Prod":"Products","Qty":"Quantity"}
df_sales = df_sales.rename(columns = rename_map)
df_sales.columns

Index(['Unnamed: 0', 'Products', 'Quantity', 'Amount', 'Region', 'Customer'], dtype='object')

In [60]:
high_sales = df_sales['Amount'] > 2000
high_sales

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7    False
8    False
9     True
Name: Amount, dtype: bool

In [61]:
df_high = df_sales[high_sales]
len(df_high)

5

In [62]:
df_high

   Unnamed: 0 Products  Quantity   Amount Region Customer
0           0   Mobile      10.0  12000.0  south    Rahul
1           1   Laptop       NaN  45000.0  north   SHREYA
4           4   Camera       2.0  55000.0  south      NaN
5           5   Tablet       NaN  12172.8  north    Rohan
9           9  Speaker       6.0   3200.0   west   Vikram

In [63]:
#combine the multiple conditions with & and |
cond_amount = df['Amount'] > 2000
cond_region = df['Region'] == "south"

In [65]:
#To extract the product detail with amount > 2000 from south
df_target = df_sales[cond_amount & cond_region]
df_target

   Unnamed: 0 Products  Quantity   Amount Region Customer
0           0   Mobile      10.0  12000.0  south    Rahul
4           4   Camera       2.0  55000.0  south      NaN

In [66]:
df_target = df_sales[cond_amount | cond_region]
df_target

   Unnamed: 0 Products  Quantity   Amount Region Customer
0           0   Mobile      10.0  12000.0  south    Rahul
1           1   Laptop       NaN  45000.0  north   SHREYA
4           4   Camera       2.0  55000.0  south      NaN
8           8  Monitor       NaN     12.0  south      NaN
9           9  Speaker       6.0   3200.0   west   Vikram

In [67]:
df_sorted = df_sales.sort_values("Amount", ascending=False)
df_sorted

   Unnamed: 0    Products  Quantity   Amount Region Customer
4           4      Camera       2.0  55000.0  south      NaN
1           1      Laptop       NaN  45000.0  north   SHREYA
5           5      Tablet       NaN  12172.8  north    Rohan
0           0      Mobile      10.0  12000.0  south    Rahul
9           9     Speaker       6.0   3200.0   west   Vikram
7           7    Keyboard       4.0   1508.0   east  Karthik
2           2  Headphones       5.0   1500.0   west    Arjun
3           3     Charger       3.0   1200.0   east    Meera
6           6       Mouse       7.0    800.0   west    Anita
8           8     Monitor       NaN     12.0  south      NaN

In [69]:
df_sorted = df_sales.sort_values(["Region","Amount"])
df_sorted

   Unnamed: 0    Products  Quantity   Amount Region Customer
3           3     Charger       3.0   1200.0   east    Meera
7           7    Keyboard       4.0   1508.0   east  Karthik
5           5      Tablet       NaN  12172.8  north    Rohan
1           1      Laptop       NaN  45000.0  north   SHREYA
8           8     Monitor       NaN     12.0  south      NaN
0           0      Mobile      10.0  12000.0  south    Rahul
4           4      Camera       2.0  55000.0  south      NaN
6           6       Mouse       7.0    800.0   west    Anita
2           2  Headphones       5.0   1500.0   west    Arjun
9           9     Speaker       6.0   3200.0   west   Vikram

In [72]:
#creating the derived column using algorithmic opeartion
#creating the "Tax" column by 10% of Amount
df_sales["Tax"] = df_sales["Amount"] * 0.10

In [73]:
df_sales

   Unnamed: 0    Products  Quantity   Amount Region Customer      Tax
0           0      Mobile      10.0  12000.0  south    Rahul  1200.00
1           1      Laptop       NaN  45000.0  north   SHREYA  4500.00
2           2  Headphones       5.0   1500.0   west    Arjun   150.00
3           3     Charger       3.0   1200.0   east    Meera   120.00
4           4      Camera       2.0  55000.0  south      NaN  5500.00
5           5      Tablet       NaN  12172.8  north    Rohan  1217.28
6           6       Mouse       7.0    800.0   west    Anita    80.00
7           7    Keyboard       4.0   1508.0   east  Karthik   150.80
8           8     Monitor       NaN     12.0  south      NaN     1.20
9           9     Speaker       6.0   3200.0   west   Vikram   320.00

In [92]:
df_sales["TotalWithTax" ] = df_sales['Amount'] + df_sales["Tax"]
df_sales

,Unnamed: 0,Products,Quantity,Amount,Region,Customer,Tax,TotalWithTax
0,0,Mobile,10.0,12000.0,south,Rahul,1200.00,13200.00
1,1,Laptop,NaN,45000.0,north,SHREYA,4500.00,49500.00
2,2,Headphones,5.0,1500.0,west,Arjun,150.00,1650.00
3,3,Charger,3.0,1200.0,east,Meera,120.00,1320.00
4,4,Camera,2.0,55000.0,south,NaN,5500.00,60500.00
5,5,Tablet,NaN,12172.8,north,Rohan,1217.28,13390.08
6,6,Mouse,7.0,800.0,west,Anita,80.00,880.00
7,7,Keyboard,4.0,1508.0,east,Karthik,150.80,1658.80
8,8,Monitor,NaN,12.0,south,NaN,1.20,13.20
9,9,Speaker,6.0,3200.0,west,Vikram,320.00,3520.00

In [94]:
#To count the occurance of values (in categorica)
df_sales = df_sales["Region"].value_counts()
df_sales

Region
south    3
west     3
north    2
east     2
Name: count, dtype: int64

In [ ]:
df_sales["Amount"].describe()

In [76]:
grp_region = df_sales.groupby("Region")
sales_by_region = grp_region["Amount"].sum()

In [77]:
sales_by_region

Region
east      2708.0
north    57172.8
south    67012.0
west      5500.0
Name: Amount, dtype: float64

In [81]:
#view the group names
grp_region.groups.keys()

dict_keys(['east', 'north', 'south', 'west'])

In [79]:
grp_region.groups

{'east': [3, 7], 'north': [1, 5], 'south': [0, 4, 8], 'west': [2, 6, 9]}

In [80]:
#view one specific group
grp_region.get_group("south")

   Unnamed: 0 Products  Quantity   Amount Region Customer     Tax
0           0   Mobile      10.0  12000.0  south    Rahul  1200.0
4           4   Camera       2.0  55000.0  south      NaN  5500.0
8           8  Monitor       NaN     12.0  south      NaN     1.2

In [83]:
#Loop through the groups (to display the content of each group)
for name, group in grp_region :
    print("Group: ", name)
    print(group)

Group:  east
   Unnamed: 0  Products  Quantity  Amount Region Customer    Tax
3           3   Charger       3.0  1200.0   east    Meera  120.0
7           7  Keyboard       4.0  1508.0   east  Karthik  150.8
Group:  north
   Unnamed: 0 Products  Quantity   Amount Region Customer      Tax
1           1   Laptop       NaN  45000.0  north   SHREYA  4500.00
5           5   Tablet       NaN  12172.8  north    Rohan  1217.28
Group:  south
   Unnamed: 0 Products  Quantity   Amount Region Customer     Tax
0           0   Mobile      10.0  12000.0  south    Rahul  1200.0
4           4   Camera       2.0  55000.0  south      NaN  5500.0
8           8  Monitor       NaN     12.0  south      NaN     1.2
Group:  west
   Unnamed: 0    Products  Quantity  Amount Region Customer    Tax
2           2  Headphones       5.0  1500.0   west    Arjun  150.0
6           6       Mouse       7.0   800.0   west    Anita   80.0
9           9     Speaker       6.0  3200.0   west   Vikram  320.0

In [85]:
#Compute multiple aggregate operation for one column
region_summary = grp_region["Amount"].agg(["sum","mean","count"])

In [86]:
#Group by multiple columns (Grouping by Region and Product)
grp_rp = df_sales.groupby(["Region","Products"])

In [89]:
#Apply Aggregate on grouped columns
rp_summary = grp_rp["Amount"].sum()

In [90]:
rp_summary

Region  Products
east    Charger        1200.0
        Keyboard       1508.0
north   Laptop        45000.0
        Tablet        12172.8
south   Camera        55000.0
        Mobile        12000.0
        Monitor          12.0
west    Headphones     1500.0
        Mouse           800.0
        Speaker        3200.0
Name: Amount, dtype: float64

In [98]:
# To display content of grouped columns
for name, group in grp_rp:
    print("Group:", name)
    print(group)

Group: ('east', 'Charger')
   Unnamed: 0 Products  Quantity  Amount Region Customer    Tax  TotalWithTax
3           3  Charger       3.0  1200.0   east    Meera  120.0        1320.0
Group: ('east', 'Keyboard')
   Unnamed: 0  Products  Quantity  Amount Region Customer    Tax  TotalWithTax
7           7  Keyboard       4.0  1508.0   east  Karthik  150.8        1658.8
Group: ('north', 'Laptop')
   Unnamed: 0 Products  Quantity   Amount Region Customer     Tax  \
1           1   Laptop       NaN  45000.0  north   SHREYA  4500.0

   TotalWithTax
1       49500.0
Group: ('north', 'Tablet')
   Unnamed: 0 Products  Quantity   Amount Region Customer      Tax  \
5           5   Tablet       NaN  12172.8  north    Rohan  1217.28

   TotalWithTax
5      13390.08
Group: ('south', 'Camera')
   Unnamed: 0 Products  Quantity   Amount Region Customer     Tax  \
4           4   Camera       2.0  55000.0  south      NaN  5500.0

   TotalWithTax
4       60500.0
Group: ('south', 'Mobile')
   Unnamed: 0 Products  Quantity   Amount Region Customer     Tax  \
0           0   Mobile      10.0  12000.0  south    Rahul  1200.0

   TotalWithTax
0       13200.0
Group: ('south', 'Monitor')
   Unnamed: 0 Products  Quantity  Amount Region Customer  Tax  TotalWithTax
8           8  Monitor       NaN    12.0  south      NaN  1.2          13.2
Group: ('west', 'Headphones')
   Unnamed: 0    Products  Quantity  Amount Region Customer    Tax  \
2           2  Headphones       5.0  1500.0   west    Arjun  150.0

   TotalWithTax
2        1650.0
Group: ('west', 'Mouse')
   Unnamed: 0 Products  Quantity  Amount Region Customer   Tax  TotalWithTax
6           6    Mouse       7.0   800.0   west    Anita  80.0         880.0
Group: ('west', 'Speaker')
   Unnamed: 0 Products  Quantity  Amount Region Customer    Tax  TotalWithTax
9           9  Speaker       6.0  3200.0   west   Vikram  320.0        3520.0

In [99]:
#Column aggregation
summary = df_sales.groupby("Region").agg(
    Total_Amount = ("Amount", "sum"),
    Avg_Amount = ("Amount", "mean"),
    Total_Tax = ("Tax", "sum"),
    Avg_Tax = ("Tax","mean"),
    Total_Quantity = ("Quantity","sum"),
    Unique_Customers = ("Customer","nunique")
)

TypeError: func is expected but received tuple in **kwargs.

In [1]:
import matplotlib.pyplot as plt
plt.hist(df['RUNNER_MINS'], bins=20)
plt.xlabel('Minutes')
plt.ylabel('Frequency')
plt.show()

Matplotlib is building the font cache; this may take a moment.

NameError: name 'df7' is not defined